apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: ophzynk
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ophzynk
  namespace: ophzynk
  labels:
    app: ophzynk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ophzynk
  template:
    metadata:
      labels:
        app: ophzynk
    spec:
      containers:
      - name: ophzynk
        image: ophzynk
        livenessProbe:
          failureThreshold: 3
          exec:
            command:
              - /ophzynk/health.sh
          initialDelaySeconds: 30
          periodSeconds: 30