apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: cluster
  namespace: kafka
spec:
  spec:
    clusterCa:
      generateCertificateAuthority: false
    clientsCa:
      generateCertificateAuthority: false
  kafka:
    version: 2.5.0
    replicas: 1
    jvmOptions:
      "-Xmx": "4g"
      "-Xms": "2g"
    listeners:
      plain: {}
      tls:
        authentication:
          type: tls
      external:
        type: nodeport
        tls: false
    authorization:
      type: simple
      superUsers:
        - CN=mirrormaker
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}